version: "2"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION:-1.19.7}
    volumes:
      - code:/var/www/html:ro
    networks:
      - reverse-proxy
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${PROJECT_HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${COMPOSE_PROJECT_NAME}@docker"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}.headers.accessControlAllowMethods=GET,HEAD,POST,PUT,DELETE,CONNECT,OPTIONS,TRACE,PATCH"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}.headers.accessControlAllowOrigin=*"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}.headers.accessControlAllowHeaders=*"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}.headers.accessControlMaxAge=600"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}.headers.addVaryHeader=true"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.0.2}
        COMPOSER_VERSION: ${COMPOSER_VERSION:-2.0.9}
        NODE_VERSION: ${NODE_VERSION:-14.16.0}
    volumes:
      - code:/var/www/html
      - composer:/var/www/.composer
      - npm:/var/www/.npm
    networks:
      - app
      - db

  db:
    image: mariadb:${MARIADB_VERSION:-10.5.8}
    volumes:
      - db:/var/lib/mysql
    networks:
      - db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  adminer:
    build:
      context: ./adminer
      dockerfile: Dockerfile
    networks:
      - reverse-proxy
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_db.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_db.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_db.rule=Host(`${ADMINER_HOST}`)"

  mutagen:
    image: alpine:${ALPINE_VERSION:-3.13.1}
    container_name: ${COMPOSE_PROJECT_NAME}_mutagen
    volumes:
      - code:/var/www/html
    command: tail -f /dev/null

networks:
  reverse-proxy:
    external: true
  app:
  db:

volumes:
  code:
  db:
  composer:
  npm:
